ENV["RAILS_ENV"] = "test"
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

# Sets up the Rails environment for Cucumber
require 'spork'
require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')

Spork.prefork do
  require "rails/application"
  Spork.trap_method(Rails::Application::RoutesReloader, :reload!)

  require "cucumber/rails"

  Capybara.javascript_driver = :webkit

  Capybara.default_selector = :css

  if Spork.using_spork?
    require 'selenium/webdriver'
    Selenium::WebDriver::Chrome::Service.executable_path = "/usr/local/bin/chromedriver"
  end

  Rails.logger.level = 4 # <=> fatal

  DatabaseCleaner.strategy = :transaction

  Cucumber::Rails::Database.javascript_strategy = :truncation
end

Spork.each_run do
  # This code will be run each time you run your specs.
  require 'factory_girl_rails'
  include FactoryGirl::Syntax::Methods
end